spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
    h2:
        console:
            enabled: true
            path: /h2
            settings:
                trace: true
                web-allow-others: false
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: false
                show_sql: false
                use_sql_comments: false