SwaggerConfig:
  Description: KTM Times REST API
  Email: support@ktmtimes.com
  License: KTM Times API License
  LicenseUrl: www.ktmtimes.com
  Name: KTM Times REST API
  TermsofServiceUrl: www.ktmtimes.com
  Title: KTM App
  Url: www.ktmtimes.com
  Version: Rest API for Javascript Clients as well as Mobile Clients
springfox:
  documentation:
    swagger:
      v2:
        path: /swagger.json
endpoints:
  health:
    sensitive: false
    db:
      enabled: true
  metrics:
    sensitive: false
info:
  app:
    description: KTM Times App
    name: ktm times
    version: 1.0.0
management:
  address: '127.0.0.1 '
  context-path: /manage
  endpoints:
    web:
      exposure:
        include: '*'
  port: 8081.0
  security:
    enabled: false
spring:
  security:
    basic:
      enabled: false
    user:
      name: pradip
      password: pradip
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  path: /var/log/ktm-api
  file: '${logging.path}/ktm-api.log'
  pattern:
    file: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
    console: '%d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n'
