spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://docker.for.mac.localhost:33061/ktm?useSSL=false
        url: jdbc:mysql://localhost:33061/ktm?useSSL=false
        username: root
        password: secret
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                show_sql: true
                use_sql_comments: true
endpoints:
    health:
        sensitive: false
        db:
            enabled: true
    metrics:
        sensitive: false
management:
    address: '127.0.0.1 '
    context-path: /manage
    endpoints:
        web:
            exposure:
                include: '*'
    port: 8081.0
    security:
        enabled: false                
