spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://docker.for.mac.localhost:33061/ktm?useSSL=false
        url: jdbc:mysql://localhost:33061/ktm?useSSL=false
        username: root
        password: secret
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
                show_sql: true
<<<<<<< HEAD
                use_sql_comments: true
                
=======
                use_sql_comments: true
>>>>>>> encrypt decrypt test
